### ISSUE TITLE
It's a great work

### ISSUE THREAD

**Issue by warmhug** [Microsoft/backbone-virtualized-listview#2]
Hi, I feel this is a great implement of virtualized-listview, but this awesome work is based on backbone, why not base React.js? Or would you consider doing a react version? It will be a great help for my https://github.com/react-component/m-list-view . Thank you.

**Comment by lyweiwei** [comment]
Sorry for replying late. We implemented the library based on our business requirement. We have a Backbone site to support :)

I know the React.js is the industry trend, and I personally like it very much, but I don't have too much time to work on it.
If you are developing a react version of virtualized list view, you're very welcomed to use the fast-binary-indexed-tree package, which maintains the segmentation height.
